project_id = "hssxrcsnxhegtcpchxhb"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-credit-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
