project_id = "hssxrcsnxhegtcpchxhb"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-credit-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-user-projects]
verify_jwt = false

[functions.create-user-project]
verify_jwt = false

[functions.delete-user-project]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.runware-api]
verify_jwt = false

[functions.get-project]
verify_jwt = false

[functions.update-project]
verify_jwt = false

[functions.deduct-credits]
verify_jwt = false

[functions.get-user-credits]
verify_jwt = false
