// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hssxrcsnxhegtcpchxhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzc3hyY3NueGhlZ3RjcGNoeGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MjIzMzYsImV4cCI6MjA2MjQ5ODMzNn0.5LO_G1x91Xa1a_tAO5HquPPcpSmepu8ePMReaqr-hlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);